# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12edeb146c9758787a6e9b0f0cf3d0af969b0e6d5ca3167efea386df8be46893b67694a87ea1c0b44341086b37a0b32a1bea48960fcecdaa23a032366e28cbd6

test:
  secret_key_base: dfbf119a56dfcc8ec5b94b291cbed1d5474ae2260a56e0367ee54c6d77fc9f35e61ff2dc833d98bae9e1e165a9583141d4c078ca7e686a52477b623f4a609523

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
